[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3001"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
