services:
  - type: web
    name: enterprise-crm-backend
    env: node
    plan: free
    buildCommand:  cd backend && npm ci --only=production && npm rebuild sqlite3 bcrypt
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com
  
  - type: web
    name: enterprise-crm-frontend
    env: static
    plan: free
    buildCommand: cd startup-crm && npm install && npm run build
    staticPublishPath: startup-crm/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
